apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-creds.yaml
  - httproute.yaml

helmCharts:
  - name: couchdb
    repo: https://apache.github.io/couchdb-helm
    version: 4.6.0
    releaseName: "obsidian-sync"
    includeCRDs: true
    namespace: db
    valuesFile: values.yaml

