# -- the initial number of nodes in the CouchDB cluster.
clusterSize: 3

networkPolicy:
  enabled: false

# Use a service account
serviceAccount:
  enabled: true
  create: true

createAdminSecret: false

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  storageClass: "longhorn-retain"

persistentVolumeClaimRetentionPolicy:
  enabled: true
  whenScaled: Retain
  whenDeleted: Retain

## The CouchDB image
image:
  pullPolicy: IfNotPresent

# -- couchdbConfig will override default CouchDB configuration settings.
couchdbConfig:
  couchdb:
   uuid: "<path:argocd:common-secrets#couchdb-uuid>"
  chttpd:
    bind_address: any
    # enable CORS on the HTTP interface
    enable_cors: "true"
    # chttpd.require_valid_user disables all the anonymous requests to the port
    # 5984 when is set to true.
    require_valid_user: true
  cors:
    # match your --data '"app://obsidian.md,capacitor://localhost,http://localhost"'
    origins: "app://obsidian.md,capacitor://localhost,http://localhost"
    credentials: "true"
    methods: "GET, PUT, POST, HEAD, DELETE"
    headers: "accept, authorization, content-type, origin, referer"