apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeops
  namespace: argocd
spec:
  project: default
  source:
    path: argocd-apps
    repoURL: git@gitlab.com:ak-home-lab/homeops.git
    targetRevision: HEAD
  destination:
    namespace: argocd
    name: in-cluster
