apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml

helmCharts:
  - name: openspeedtest
    repo: https://openspeedtest.github.io/Helm-chart/
    version: 0.1.2
    releaseName: openspeedtest
    namespace: speedtest
    valuesFile: values.yaml
