apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.22.0
    releaseName: "cnpg-db-operator"
    includeCRDs: true
    namespace: db
    valuesFile: values.yaml

