apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    path: bootstrap/cilium
    repoURL: https://github.com/kha7iq/homeops.git
    targetRevision: HEAD
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - ServerSideApply=true     
