apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    path: bootstrap/external-secrets
    repoURL: https://github.com/kha7iq/homeops.git
    targetRevision: HEAD
  destination:
    namespace: external-secrets
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true     
