apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  source:
    path: argocd-apps/observability
    repoURL: https://github.com/kha7iq/homeops.git
    targetRevision: HEAD
  destination:
    namespace: argocd
    name: in-cluster
