apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tsig-key
  namespace: external-dns
spec:
  secretStoreRef:
    name: bitwarden-cluster-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: "0"
  data:
    - secretKey: key
      remoteRef:
        key: tsig-key
