
sources:
  - service
  - gateway-httproute
  - gateway-grpcroute
  - gateway-tlsroute


# -- How DNS records are synchronized between sources and providers; available values are `sync` & `upsert-only`.
policy: sync

serviceMonitor:
  enabled: true


provider:
  name: rfc2136

# -- Extra arguments to provide to _ExternalDNS_.
extraArgs:
  - --rfc2136-host=192.168.0.21
  - --rfc2136-port=53
  - --rfc2136-zone=<path:argocd:common-secrets#homelab-domain>
  - --rfc2136-zone=noip.pk
  - --rfc2136-tsig-secret-alg=hmac-sha256
  - --rfc2136-tsig-keyname=external-dns
  - --rfc2136-tsig-axfr

env:
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: tsig-key
        key: key