apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authentik-creds.yml
  - httproute.yaml
  - css-configmap.yaml

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    version: 2025.4.0
    releaseName: authentik
    namespace: authentik
    valuesFile: values.yaml