
nodeSelector:
  kubernetes.io/arch: amd64

serviceMonitor:
  enabled: true

spegel:
  registries:
    - https://cgr.dev
    - https://docker.io
    - https://ghcr.io
    - https://quay.io
    - https://mcr.microsoft.com
    - https://public.ecr.aws
    - https://gcr.io
    - https://registry.k8s.io
    - https://k8s.gcr.io
    - https://lscr.io
    - https://registry.gitlab.com

  containerdRegistryConfigPath: "/etc/cri/conf.d/hosts"
 