apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - httproute.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    releaseName: lmno
    namespace: web
    version: 3.5.1
    valuesFile: values.yaml
