apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homeops-postgresql
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/hook: PostSync
spec:
  description: "PostgreSQL Cluster HomeOps"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 3
  primaryUpdateStrategy: unsupervised
# Enbale Monitoring of the cluster based on a configmap created before.
  monitoring:
    enablePodMonitor: true
    customQueriesConfigMap:
      - name: cnpg-default-monitoring
        key: queries
# Create a super user when deploying cluster
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-credentials
# Persistent Storage 
  storage:
    storageClass: longhorn-db
    size: 10Gi

# Backup properties
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-backup/
      endpointURL: http://192.168.0.20:9000
      s3Credentials:
        accessKeyId:
          name: pg-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: pg-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        additionalCommandArgs:
          - "--min-chunk-size=5MB"
          - "--read-timeout=60"

    retentionPolicy: "15d"
