apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-backup-schedule
  namespace: db
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  suspend: false
  cluster:
    name: homeops-postgresql
