replicaCount: 1
image:
  repository: ghcr.io/project-zot/zot
  pullPolicy: IfNotPresent
  # tag: "v2.1.17"
namespace: ""
serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 5000
  nodePort: null
  annotations: {}
  clusterIP: null


# If mountConfig is true the configMap named $CHART_RELEASE-config is mounted
# on the pod's '/etc/zot' directory
mountConfig: true
configFiles:
  config.json: |-
    {
      "storage": { "rootDirectory": "/var/lib/registry" },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "readTimeout": "60s",
        "writeTimeout": "60s",
        "externalURL": "https://registry.<path:argocd:common-secrets#homelab-domain>"
      },
      "log": { "level": "info" }
    }

persistence: true
pvc:
  create: true
  name: null
  accessModes: ["ReadWriteOnce"]
  storage: 20Gi
  storageClassName: longhorn-retain

strategy:
  type: RollingUpdate

