replicaCount: 1

image:
  repository: ghcr.io/project-zot/zot-linux-amd64
  pullPolicy: IfNotPresent
  # tag: "v2.1.17"

namespace: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 5000
  nodePort: null
  annotations: {}
  clusterIP: null

env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: zot-rustfs-creds
        key: accesskey
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: zot-rustfs-creds
        key: secretkey

externalSecrets:
  - secretName: "zot-oidc-creds"
    mountPath: "/etc/zot/oidc"
  - secretName: "zot-htpasswd"
    mountPath: "/etc/zot/htpasswd"

mountConfig: true

configFiles:
  config.json: |-
    {
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "dedupe": false,
        "storageDriver": {
          "name": "s3",
          "region": "us-east-1",
          "regionendpoint": "http://192.168.0.20:9000",
          "bucket": "zot-registry",
          "secure": false,
          "skipverify": false,
          "forcepathstyle": true
        }
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "readTimeout": "60s",
        "writeTimeout": "60s",
        "externalUrl": "https://registry.<path:argocd:common-secrets#homelab-domain>",
        "compat": ["docker2s2"],
        "auth": {
          "htpasswd": {
            "path": "/etc/zot/htpasswd/htpasswd"
          },
          "openid": {
            "providers": {
              "oidc": {
                "name": "Authentik",
                "credentialsFile": "/etc/zot/oidc/oidc-credentials.json",
                "issuer": "https://auth.<path:argocd:common-secrets#homelab-domain>/application/o/zot/",
                "keypath": "",
                "scopes": ["openid", "profile", "email", "groups"]
              }
            }
          }
        }
      },
      "extensions": {
        "search": {
          "enable": true
        },
        "ui": {
          "enable": true
        },
        "trust": {
          "enable": true,
          "cosign": true
        }
      },
      "log": {
        "level": "info"
      }
    }

strategy:
  type: RollingUpdate
