apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-tektonops
  namespace: gateway
spec:
  dnsNames:
    - "*.tektonops.com"
    - tektonops.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-tektonops
  usages:
    - digital signature
    - key encipherment
