apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netbird-agent
  namespace: netbird
spec:
  selector:
    matchLabels:
      app: netbird
  template:
    metadata:
      labels:
        app: netbird
    spec:
      containers:
        - name: netbird
          image: docker.io/netbirdio/netbird:0.36.5 # renovate: docker=docker.io/netbirdio/netbird
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              add: [ NET_ADMIN, PERFMON, BPF ]
          envFrom:
            - configMapRef:
                name: agent-config
          env:
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  name: netbird-agent-setup-key
                  key: setupKey
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: { }
