apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbird-agent-setup-key
  annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: bitwarden-cluster-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: "0"
  data:
    - secretKey: setupKey
      remoteRef:
        key: netbird-agent-setup-key
