apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - http-route.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 70.5.0
    releaseName: "kube-prometheus-stack"
    namespace: prometheus-stack
    valuesFile: values.yaml

