apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - paperless-creds.yaml
  - httproute.yaml

helmCharts:
  - name: paperless-ngx
    repo: https://charts.gabe565.com
    releaseName: paperless-ngx
    namespace: paperless
    version: 0.19.1
    valuesFile: values.yaml
