apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-sso-creds.yaml
  - httproute.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 8.12.0
    releaseName: grafana
    namespace: grafana
    valuesFile: values.yaml

